# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: go_fortunes
version: 2
builds:
    - id: fortunes-generator
      binary: '{{.ProjectName}}_{{envOrDefault "_VERSION" "DEV"}}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
      no_unique_dist_dir: true
      mod_timestamp: "{{ .CommitTimestamp }}"
      goos:
          - linux
          - windows
          # - freebsd
          # - openbsd
      goarch:
          - amd64
          - arm
          - arm64
          # - loong64
          # - ppc64le
          # - s390x
      goarm:
          - 5
          - 6
          - 7
      flags:
          - -trimpath
      ignore:
          - goos: freebsd
            goarch: arm
          - goos: openbsd
            goarch: arm
          - goos: freebsd
            goarch: arm64
          - goos: openbsd
            goarch: arm64
dist: "./dist"
checksum:
    algorithm: sha256
    split: false
